# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
bioc_required: true

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
  - Rscript -e 'covr::coveralls(type = "all")'  